spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.uri=mongodb+srv://district:district@cospace.81zxqez.mongodb.net/cospace?retryWrites=true&w=majority