# docker-compose.yaml

version: '3'
services:
  # MongoDB Service
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017  # Exposing MongoDB on the default port
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
    command: mongod --auth

  # Mongo Express (UI) Service
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo  # Refers to the mongo service
    ports:
      - 8081:8081  # Exposing Mongo Express on port 8081
    depends_on:
      - mongo  # Wait for MongoDB to be up before starting Mongo Express
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local